### ISSUE TITLE
vroom/readr not working

### ISSUE THREAD

**Issue by Jason-Conner-NOAA** [ben-williams/swo-sim#1]
Attempting to load downloaded csv files created by Pete's query code using vroom and readr and get the following error:

Error in app$vspace(new_style$`margin-top` %||% 0) :                                                               
  attempt to apply non-function

Only 2 references to this error on the web. Any ideas? read.csv() does work.

**Comment by Jason-Conner-NOAA** [comment]
This does not occur on a different environment, reference readr issue: https://github.com/tidyverse/readr/issues/1371

**Comment by BenWilliams-NOAA** [comment]
Sorry missed this! haven't seen that one before. Did you figure this out, if not could you point me to the query code that is causing the issue(s)

**Comment by Jason-Conner-NOAA** [comment]
It looks like a versioning issue with no real solution. Closing this because it is working on my gov't laptop, but not my personal desktop.
