### ISSUE TITLE
also tinkering

### ISSUE THREAD

**Issue by pete-hulson** [ben-williams/swo-sim#10]
https://github.com/ben-williams/swo-sim/blob/90c6300fa47b1d6e5dca34339105f7c0fb2a25be/R/functions.R#L371

same as last issue, if we add:

      mutate(in_out = ifelse(is.infinite(value), "out", "in")) %>%
      group_by(sim, year, species_code, ess, value, in_out) %>%
      distinct(value) -> .out

here we can reduce output file size

**Comment by BenWilliams-NOAA** [comment]
added
