### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by mdbryan** [ben-williams/swo-sim#15]
https://github.com/ben-williams/swo-sim/blob/a3349d0e4953bb2b6cd4949dc99e674d9ceba418/R/functions.R#L136

Encountering the following error when trying to run for stratum sims:
Error in `mutate()`:
! Problem while computing `..1 = across(tidyr::everything(), ~replace_na(.x, 0))`.
i The error occurred in group 1: species_code = 10110.
Caused by error in `across()`:
! Problem while computing column `stratum`.
Caused by error in `stop_vctrs()`:
! Can't convert `replace` <double> to match type of `data` <character>

In line 135 the left.join changes the 'TRUE' in column na.rm to NA. If do not  run the left.join the mutate statement on line 136 works, so I think the change from TRUE to NA in the na.rm column is causing problems.

**Comment by BenWilliams-NOAA** [comment]
corrected
