### ISSUE TITLE
nother slight change to functions

### ISSUE THREAD

**Issue by pete-hulson** [ben-williams/swo-sim#8]
https://github.com/ben-williams/swo-sim/blob/30f0b97b077c584a8e9ec5dea4cfe253523cfb99/R/functions.R#L174

if we switch this and next line to:

      group_by(year, species_code, stratum, hauljoin) %>%
      summarise(ss_removed = length(id)/iters) -> .removed_summ

it'll give an even more summarized version (the samples removed are consistent and repeated across iterations)

**Comment by BenWilliams-NOAA** [comment]
added
