### ISSUE TITLE
kepp on tinkering

### ISSUE THREAD

**Issue by pete-hulson** [ben-williams/swo-sim#9]
https://github.com/ben-williams/swo-sim/blob/90c6300fa47b1d6e5dca34339105f7c0fb2a25be/R/functions.R#L350

if we add:

      mutate(in_out = ifelse(is.infinite(value), "out", "in")) %>%
      group_by(sim, year, species_code, stratum, ess, value, in_out) %>%
      distinct(value) -> .out

here we can reduce the output file size by only keeping the unique ess estimates, we also don't need to keep the pop'n at length estimates as those are in the _comp output

**Comment by BenWilliams-NOAA** [comment]
added
